// Package userservice owns deterministic user-scoped Aegis service lifecycle.
// It never installs a system service, enables linger, or embeds credentials.
package userservice

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net"
	"net/http"
	"os"
	"os/exec"
	"os/user"
	"path/filepath"
	"strconv"
	"strings"
	"syscall"
	"time"

	"github.com/berryhill/aegis/internal/config"
)

const (
	UnitName     = "aegis.service"
	Confirmation = "INSTALL AEGIS USER SERVICE"
)

var (
	ErrForeignUnit         = errors.New("existing user unit is not owned by this exact Aegis plan")
	ErrServiceNotInstalled = errors.New("service_not_installed: Aegis user service is not installed; run `aegis service install`")
)

// ActivationError identifies the failed phase and preserves rollback evidence.
type ActivationError struct {
	Phase       string
	Err         error
	RollbackErr error
}

func (e *ActivationError) Error() string {
	if e.RollbackErr != nil {
		return fmt.Sprintf("user service activation phase %q failed: %v; rollback failed: %v", e.Phase, e.Err, e.RollbackErr)
	}
	return fmt.Sprintf("user service activation phase %q failed: %v", e.Phase, e.Err)
}

func (e *ActivationError) Unwrap() []error { return []error{e.Err, e.RollbackErr} }

type Plan struct {
	UnitPath     string `json:"unit_path"`
	UnitDigest   string `json:"unit_digest"`
	Executable   string `json:"executable"`
	ConfigPath   string `json:"config_path"`
	UnixSocket   string `json:"unix_socket"`
	Origin       string `json:"console_origin"`
	Principal    string `json:"principal"`
	Confirmation string `json:"confirmation"`
	unit         []byte
}

type Runner interface {
	Run(context.Context, ...string) error
	Output(context.Context, ...string) ([]byte, error)
}

type Systemctl struct{ Executable string }

func (s Systemctl) Run(ctx context.Context, args ...string) error {
	path := s.Executable
	if path == "" {
		path = "systemctl"
	}
	command := exec.CommandContext(ctx, path, append([]string{"--user"}, args...)...)
	command.Stdin = nil
	command.Stdout = nil
	var diagnostic bytes.Buffer
	command.Stderr = &diagnostic
	if err := command.Run(); err != nil {
		return fmt.Errorf("systemctl --user %s: %s: %w", strings.Join(args, " "), strings.TrimSpace(diagnostic.String()), err)
	}
	return nil
}

func (s Systemctl) Output(ctx context.Context, args ...string) ([]byte, error) {
	path := s.Executable
	if path == "" {
		path = "systemctl"
	}
	command := exec.CommandContext(ctx, path, append([]string{"--user"}, args...)...)
	command.Stdin = nil
	var output, diagnostic bytes.Buffer
	command.Stdout = &output
	command.Stderr = &diagnostic
	if err := command.Run(); err != nil {
		return nil, fmt.Errorf("systemctl --user %s: %s: %w", strings.Join(args, " "), strings.TrimSpace(diagnostic.String()), err)
	}
	return output.Bytes(), nil
}

func Preview(executable, configPath string) (Plan, error) {
	executable, err := filepath.Abs(executable)
	if err != nil {
		return Plan{}, err
	}
	if info, statErr := os.Stat(executable); statErr != nil || !info.Mode().IsRegular() || info.Mode().Perm()&0111 == 0 {
		return Plan{}, errors.New("Aegis executable must be one absolute executable regular file")
	}
	inspection := config.Inspect(configPath)
	if inspection.State != config.StateValid || !inspection.FilePresent {
		return Plan{}, errors.New("user service requires one secure file-backed valid configuration")
	}
	cfg := inspection.Config
	if cfg.API.Token == "" || cfg.API.TokenFile == "" || cfg.API.UnixSocket == "" {
		return Plan{}, errors.New("serve-ready protected token_file and unix_socket are required")
	}
	current, err := user.Current()
	if err != nil || current.Uid != cfg.Principal.UID || current.Username != cfg.Principal.User {
		return Plan{}, errors.New("configured principal does not match freshly authenticated host identity")
	}
	unitDir, err := userUnitDirectory()
	if err != nil {
		return Plan{}, err
	}
	unit := []byte(fmt.Sprintf("# Generated by Aegis; digest-bound user service.\n[Unit]\nDescription=Aegis authenticated local control plane\nAfter=network.target\n\n[Service]\nType=simple\nExecStart=%s serve --config %s\nRestart=on-failure\nRestartSec=2s\nTimeoutStopSec=%s\nKillMode=control-group\nKillSignal=SIGTERM\nUMask=0077\nNoNewPrivileges=true\n\n[Install]\nWantedBy=default.target\n", systemdQuote(executable), systemdQuote(inspection.Path), cfg.API.ShutdownTimeout))
	digest := sha256.Sum256(unit)
	return Plan{UnitPath: filepath.Join(unitDir, UnitName), UnitDigest: hex.EncodeToString(digest[:]), Executable: executable, ConfigPath: inspection.Path, UnixSocket: cfg.API.UnixSocket, Origin: cfg.API.Console.Origin, Principal: current.Username + " (UID " + current.Uid + ")", Confirmation: Confirmation, unit: unit}, nil
}

func Installed(plan Plan) (bool, error) {
	if _, err := os.Lstat(plan.UnitPath); errors.Is(err, os.ErrNotExist) {
		return false, nil
	} else if err != nil {
		return false, err
	}
	if err := inspectUnit(plan.UnitPath, plan.unit); err != nil {
		return false, err
	}
	return true, nil
}

func Apply(ctx context.Context, plan Plan, runner Runner, timeout time.Duration) error {
	if runner == nil {
		return errors.New("user service manager is unavailable")
	}
	current, err := Preview(plan.Executable, plan.ConfigPath)
	if err != nil {
		return err
	}
	if !samePlan(current, plan) {
		return errors.New("user service plan drifted after preview")
	}
	if err = inspectUnit(plan.UnitPath, plan.unit); err != nil {
		return err
	}
	active, err := serviceState(ctx, runner, "ActiveState")
	if err != nil {
		return activationFailure("capture_state", err, nil)
	}
	enabled, err := serviceState(ctx, runner, "UnitFileState")
	if err != nil {
		return activationFailure("capture_state", err, nil)
	}
	if err = os.MkdirAll(filepath.Dir(plan.UnitPath), 0700); err != nil {
		return activationFailure("publish", err, nil)
	}
	published, err := publishUnit(plan.UnitPath, plan.unit)
	if err != nil {
		return activationFailure("publish", err, nil)
	}
	rollback := func() error {
		var rollbackErrs []error
		if !enabled {
			rollbackErrs = appendError(rollbackErrs, runner.Run(context.Background(), "disable", UnitName))
		}
		if !active {
			rollbackErrs = appendError(rollbackErrs, runner.Run(context.Background(), "stop", UnitName))
		}
		if published {
			rollbackErrs = appendError(rollbackErrs, os.Remove(plan.UnitPath))
		}
		rollbackErrs = appendError(rollbackErrs, runner.Run(context.Background(), "daemon-reload"))
		return errors.Join(rollbackErrs...)
	}
	if err = runner.Run(ctx, "daemon-reload"); err != nil {
		return activationFailure("daemon_reload", err, rollback())
	}
	if err = runner.Run(ctx, "enable", "--now", UnitName); err != nil {
		return activationFailure("enable_start", err, rollback())
	}
	if timeout <= 0 {
		timeout = 15 * time.Second
	}
	readyCtx, cancel := context.WithTimeout(ctx, timeout)
	defer cancel()
	cfg, err := config.Load(plan.ConfigPath, nil)
	if err != nil {
		return activationFailure("authenticated_readiness", err, rollback())
	}
	if err = waitReady(readyCtx, cfg); err != nil {
		return activationFailure("audit_current_readiness", err, rollback())
	}
	return nil
}

func samePlan(left, right Plan) bool {
	return left.UnitPath == right.UnitPath && left.UnitDigest == right.UnitDigest &&
		left.Executable == right.Executable && left.ConfigPath == right.ConfigPath &&
		left.UnixSocket == right.UnixSocket && left.Origin == right.Origin &&
		left.Principal == right.Principal && left.Confirmation == right.Confirmation &&
		bytes.Equal(left.unit, right.unit)
}

func activationFailure(phase string, err, rollbackErr error) error {
	return &ActivationError{Phase: phase, Err: err, RollbackErr: rollbackErr}
}

func appendError(errs []error, err error) []error {
	if err != nil {
		return append(errs, err)
	}
	return errs
}

func serviceState(ctx context.Context, runner Runner, property string) (bool, error) {
	output, err := runner.Output(ctx, "show", UnitName, "--property", property, "--value")
	if err != nil {
		return false, err
	}
	switch strings.TrimSpace(string(output)) {
	case "active", "enabled", "enabled-runtime", "linked", "linked-runtime":
		return true, nil
	case "", "inactive", "failed", "activating", "deactivating", "disabled", "static", "masked", "masked-runtime", "not-found":
		return false, nil
	default:
		return false, fmt.Errorf("unexpected %s state %q", property, strings.TrimSpace(string(output)))
	}
}

func Action(ctx context.Context, runner Runner, plan Plan, action string) error {
	if runner == nil {
		return errors.New("user service manager is unavailable")
	}
	switch action {
	case "start", "stop", "restart":
	default:
		return errors.New("unsupported user service action")
	}
	installed, err := Installed(plan)
	if err != nil {
		return err
	}
	if !installed {
		return ErrServiceNotInstalled
	}
	return runner.Run(ctx, action, UnitName)
}

func Status(ctx context.Context, runner Runner, plan Plan) (map[string]any, error) {
	if err := inspectUnit(plan.UnitPath, plan.unit); err != nil {
		return nil, err
	}
	active, activeErr := runner.Output(ctx, "is-active", UnitName)
	linger := "unknown"
	if current, err := user.Current(); err == nil {
		if output, probeErr := exec.CommandContext(ctx, "loginctl", "show-user", current.Uid, "-p", "Linger", "--value").Output(); probeErr == nil {
			linger = strings.TrimSpace(string(output))
		}
	}
	return map[string]any{"unit": UnitName, "unit_path": plan.UnitPath, "unit_digest": plan.UnitDigest, "active": strings.TrimSpace(string(active)), "active_error": activeErr != nil, "linger": linger, "logout_survival_claimed": linger == "yes"}, nil
}

func Uninstall(ctx context.Context, plan Plan, runner Runner) error {
	if err := inspectUnit(plan.UnitPath, plan.unit); err != nil {
		return err
	}
	if err := runner.Run(ctx, "disable", "--now", UnitName); err != nil {
		return err
	}
	if err := os.Remove(plan.UnitPath); err != nil && !errors.Is(err, os.ErrNotExist) {
		return err
	}
	return runner.Run(ctx, "daemon-reload")
}

func inspectUnit(path string, expected []byte) error {
	info, err := os.Lstat(path)
	if errors.Is(err, os.ErrNotExist) {
		return nil
	}
	if err != nil {
		return err
	}
	stat, ok := info.Sys().(*syscall.Stat_t)
	if !info.Mode().IsRegular() || !ok || int(stat.Uid) != os.Geteuid() || stat.Nlink != 1 {
		return ErrForeignUnit
	}
	actual, err := os.ReadFile(path)
	if err != nil || !bytes.Equal(actual, expected) {
		return ErrForeignUnit
	}
	return nil
}

func publishUnit(path string, unit []byte) (bool, error) {
	if _, err := os.Lstat(path); err == nil {
		return false, nil
	} else if !errors.Is(err, os.ErrNotExist) {
		return false, err
	}
	temporary, err := os.CreateTemp(filepath.Dir(path), ".aegis.service.*")
	if err != nil {
		return false, err
	}
	temporaryPath := temporary.Name()
	defer os.Remove(temporaryPath)
	if err = temporary.Chmod(0600); err == nil {
		_, err = temporary.Write(unit)
	}
	if err == nil {
		err = temporary.Sync()
	}
	if closeErr := temporary.Close(); err == nil {
		err = closeErr
	}
	if err != nil {
		return false, err
	}
	if err = os.Link(temporaryPath, path); err != nil {
		return false, err
	}
	return true, nil
}

func waitReady(ctx context.Context, cfg config.Config) error {
	transport := &http.Transport{DialContext: func(ctx context.Context, _, _ string) (net.Conn, error) {
		return (&net.Dialer{}).DialContext(ctx, "unix", cfg.API.UnixSocket)
	}}
	client := &http.Client{Transport: transport, Timeout: time.Second}
	ticker := time.NewTicker(100 * time.Millisecond)
	defer ticker.Stop()
	var lastErr error
	for {
		request, _ := http.NewRequestWithContext(ctx, http.MethodGet, "http://unix/readyz", nil)
		request.Header.Set("Authorization", "Bearer "+cfg.API.Token)
		response, err := client.Do(request)
		if err == nil {
			var body struct {
				Status string `json:"status"`
				Audit  struct {
					Current    bool   `json:"current"`
					Verifiable bool   `json:"verifiable"`
					Reason     string `json:"reason"`
				} `json:"audit"`
			}
			decodeErr := json.NewDecoder(io.LimitReader(response.Body, 64<<10)).Decode(&body)
			_ = response.Body.Close()
			switch {
			case decodeErr != nil:
				lastErr = fmt.Errorf("readiness returned HTTP %d with invalid response: %w", response.StatusCode, decodeErr)
			case response.StatusCode != http.StatusOK:
				lastErr = fmt.Errorf("readiness returned HTTP %d: status=%q audit_current=%t audit_verifiable=%t reason=%q", response.StatusCode, body.Status, body.Audit.Current, body.Audit.Verifiable, body.Audit.Reason)
			case body.Status == "ready" && body.Audit.Current && body.Audit.Verifiable:
				return nil
			default:
				lastErr = fmt.Errorf("readiness not audit-current: status=%q reason=%q", body.Status, body.Audit.Reason)
			}
		} else {
			lastErr = err
		}
		select {
		case <-ctx.Done():
			return errors.Join(ctx.Err(), lastErr)
		case <-ticker.C:
		}
	}
}

func userUnitDirectory() (string, error) {
	if value := os.Getenv("XDG_CONFIG_HOME"); value != "" {
		if !filepath.IsAbs(value) {
			return "", errors.New("XDG_CONFIG_HOME must be absolute")
		}
		return filepath.Join(value, "systemd", "user"), nil
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(home, ".config", "systemd", "user"), nil
}

func systemdQuote(value string) string {
	return strconv.Quote(value)
}
