//go:build linux

package command

import (
	"context"
	"crypto/sha256"
	"debug/buildinfo"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"testing"

	"github.com/berryhill/aegis/internal/config"
	"github.com/berryhill/aegis/internal/userservice"
)

// Domain contract: exercise the installed terminal without granting a model or
// fixture credential authority. Fixture only the service-manager observation;
// every HTTP authentication/approval and canonical credential write stays real.
// No actual user unit is installed, activated, or modified. Never retain the PTY
// transcript or include generated values in subprocess arguments or diagnostics.
func installedIntakeCommand(t *testing.T, ctx context.Context, root, binary string, cfg config.Config, terminal *os.File) *exec.Cmd {
	t.Helper()
	if !filepath.IsAbs(binary) {
		t.Fatal("acceptance binary must be absolute")
	}
	body, err := os.ReadFile(binary)
	if err != nil {
		t.Fatal("acceptance binary unavailable")
	}
	digest := sha256.Sum256(body)
	if want := os.Getenv("AEGIS_INTAKE_ACCEPTANCE_SHA256"); want == "" || hex.EncodeToString(digest[:]) != want {
		t.Fatal("acceptance binary SHA256 missing or mismatched")
	}
	info, err := buildinfo.ReadFile(binary)
	if err != nil {
		t.Fatal("acceptance binary has no Go provenance")
	}
	settings := map[string]string{}
	for _, setting := range info.Settings {
		settings[setting.Key] = setting.Value
	}
	if want := os.Getenv("AEGIS_INTAKE_ACCEPTANCE_REVISION"); want == "" || settings["vcs.revision"] != want || settings["vcs.modified"] != "false" {
		t.Fatal("acceptance binary must identify the exact clean candidate")
	}
	home := filepath.Join(root, "home")
	xdg := filepath.Join(home, ".config")
	bin := filepath.Join(root, "fixture-bin")
	for _, dir := range []string{home, bin, filepath.Join(xdg, "systemd", "user")} {
		if err := os.MkdirAll(dir, 0700); err != nil {
			t.Fatal("fixture directory creation failed")
		}
	}
	write := func(path string, value []byte, mode os.FileMode) {
		t.Helper()
		if err := os.WriteFile(path, value, mode); err != nil {
			t.Fatal("protected fixture write failed")
		}
	}
	cfg.API.TokenFile = filepath.Join(root, "transport.token")
	write(cfg.API.TokenFile, []byte(cfg.API.Token), 0600)
	cfg.API.Token = ""
	configPath := filepath.Join(root, "config.json")
	encoded, err := json.Marshal(cfg)
	if err != nil {
		t.Fatal("fixture configuration encoding failed")
	}
	write(configPath, encoded, 0600)
	if got := config.Inspect(configPath); got.State != config.StateValid {
		t.Fatal("fixture configuration invalid")
	}
	// Pin the exact generated unit contract; Preview/Installed independently
	// validates these bytes. XDG is isolated from the operator's unit directory.
	t.Setenv("XDG_CONFIG_HOME", xdg)
	plan, err := userservice.Preview(binary, configPath)
	if err != nil {
		t.Fatal("fixture service preview failed")
	}
	unit := fmt.Sprintf("# Generated by Aegis; digest-bound user service.\n[Unit]\nDescription=Aegis authenticated local control plane\nAfter=network.target\n\n[Service]\nType=simple\nExecStart=%q serve --config %q\nRestart=on-failure\nRestartSec=2s\nTimeoutStopSec=%s\nKillMode=control-group\nKillSignal=SIGTERM\nUMask=0077\nNoNewPrivileges=true\n\n[Install]\nWantedBy=default.target\n", binary, configPath, cfg.API.ShutdownTimeout)
	write(plan.UnitPath, []byte(unit), 0600)
	if installed, err := userservice.Installed(plan); err != nil || !installed {
		t.Fatal("fixture unit does not match production preview")
	}
	responses, err := json.Marshal(map[string]string{
		"FragmentPath": plan.UnitPath,
		"ExecStart":    fmt.Sprintf("{ path=%s ; argv[]=%s serve --config %s ; ignore_errors=no ; }", binary, binary, configPath),
		"ActiveState":  "active",
	})
	if err != nil {
		t.Fatal("fixture observation encoding failed")
	}
	write(filepath.Join(bin, "observations.json"), responses, 0600)
	// Only these read-only queries are simulated. Any lifecycle action or
	// unexpected query exits nonzero; no real systemctl is ever invoked.
	write(filepath.Join(bin, "systemctl"), []byte(`#!/usr/bin/python3
import json, pathlib, sys
args = sys.argv[1:]
if len(args) != 6 or args[:4] != ["--user", "show", "aegis.service", "--property"] or args[5] != "--value":
    sys.exit(70)
values = json.loads(pathlib.Path(__file__).with_name("observations.json").read_text())
if args[4] not in values:
    sys.exit(71)
print(values[args[4]])
`), 0700)
	process := exec.CommandContext(ctx, binary, "manager", "--config", configPath)
	process.Env = []string{"HOME=" + home, "XDG_CONFIG_HOME=" + xdg, "PATH=" + bin + ":/usr/bin:/bin", "TERM=xterm-256color"}
	process.Dir = root
	process.Stdin, process.Stdout, process.Stderr = terminal, terminal, terminal
	return process
}
